# Generated by Django 4.1.1 on 2022-09-23 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0005_buy_delete_checkout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='buy',
            new_name='BuyNow',
        ),
    ]
