# Generated by Django 4.1.1 on 2022-09-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0007_book_pages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyNow',
            new_name='IssueBook',
        ),
        migrations.RenameField(
            model_name='issuebook',
            old_name='qty',
            new_name='quantity',
        ),
    ]
